# Overview

This project provides some basic tools for manipulating ADIF formatted data
used by many (most?) Amateur Radio Logging software. I make no claims that
these tools meet the ADIF spec 100%. They are intended to help me convert ADIF
files to Cabrillo format, make them easily readable (pretty-print), etc.

I've only tested this code with ADIF formats generated by a handful of logging
programs and adjustments may be needed to fit your specific situation.

# Contributing

If you'd like to contribute changes, please send a PR and I'll try to review.

# Getting Started

Clone the repo and start playing around. It's not sophisticated.

* adif.tcl - Provides a simple Tcl package for reading/writing ADIF formatted data
* pp_adif.tcl - Reads an ADIF formatted file and reformats it with one field per line
* adif2cabrillo.tcl - Converts an ADIF formatted file to a series of Cabrillo formatted QSO records

# Language

These utilities are written in [Tcl](https://tcl.tk) and generally use features
available in Tcl 8.5.

Why Tcl? Because I like Tcl and I know it well. When I want to "just make
something work", I typically fall back to what I know best.

# License

This repository uses the MIT license. See [license.terms](license.terms) for
details.
